### ISSUE TITLE
problem the Texture in godot 

### ISSUE THREAD

**Issue by Sorshx** [godot-hub/godot-hub#490]
There is a problem when adding Texture to material And we go to UV1 For example, 8000 
There are lines and boxes that I just hope will disappear. Thank you 
![Screenshot_٢٠٢٣١٢٠٦-٢٣٠٨٥٢](https://github.com/godot-hub/godot-hub/assets/153130532/b1695988-5254-450b-b7de-1c317f331dd8)
![Screenshot_٢٠٢٣١٢٠٦-٢٢٥٦١٩](https://github.com/godot-hub/godot-hub/assets/153130532/3166ad04-8707-407d-bb9c-a7df431f235f)
Thank you, Who can give me the answer?

**Comment by Mainman002** [comment]
Hello Sorshx, sorry we only handle downloading Godot Engine and manage project files.

But I believe what you're experiencing is either image filtering, mipmapping, or antialiasing with your texture. The svg should in theory have infinte detail as it uses math to draw shapes, but I think Godot has to convert it to a Texture2D to display it so it's probably rendering around 128px - 512px.

This might help by turning off filtering in the reimport tab when selecting the Godot icon in Godot's file browser ->
https://github.com/godotengine/godot-proposals/issues/457

This is the official github repo for Godot Engine ->
https://github.com/godotengine/godot

**Comment by Sorshx** [comment]
Thank you

**Comment by mrwanashraf** [comment]
Since this issue is irrelevant to the repo I will go ahead and close it.
